export { default as dialog } from './dialog'
export { default as friends } from './friends'
export { default as groups } from './groups'
export { default as posts } from './posts'
export { default as users } from './users'
